name: Merge branches
runs:
  using: composite
  steps:
    - name: Checkout ${{ github.event.pull_request.base.ref || 'master' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.base.ref || '' }}
        fetch-depth: 1 # shallow
        fetch-tags: false
    - name: Unshallow base branch
      shell: bash
      run: |
        git fetch --no-tags origin ${{ github.event.pull_request.base.ref || '' }} --unshallow || true
    - name: Fetch PR head
      shell: bash
      if: github.event_name == 'pull_request'
      run: |
        git fetch --no-tags origin pull/${{ github.event.number }}/head:pr-${{ github.event.number }}
    - name: Merge PR into base
      shell: bash
      if: github.event_name == 'pull_request'
      run: |
        git config user.name "BBB Automated Tests"
        git config user.email "tests@bigbluebutton.org"
        git checkout ${{ github.event.pull_request.base.ref || '' }}
        git merge --no-ff --no-edit pr-${{ github.event.number }}
