name: Merge branches
runs:
  using: composite
  steps:
    - name: Checkout PR's source merged into its target branch
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v4
      with:
        ref: refs/pull/${{ github.event.number }}/merge

    - name: Checkout commit/branch
      if: github.event_name != 'pull_request'
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
