name: Create and Publish Docker Image

on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout ${{ github.event.pull_request.base.ref }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0 # Fetch all history
      - name: Merge pr-${{ github.event.number }} into ${{ github.event.pull_request.base.ref }}
        run: |
          git config user.name "BBB Automated Tests"
          git config user.email "tests@bigbluebutton.org"
          git config pull.rebase false
          git pull origin pull/${{ github.event.number }}/head:${{ github.head_ref }}
